### ISSUE TITLE
Look forward the code and pretrained model

### ISSUE THREAD

**Issue by JoshonSmith** [Yueziyu/RainDirection-and-Real3000-Dataset#1]

**Comment by Yueziyu** [comment]
Thanks for your attention to our work, the code and models will be published in the attached link to the paper, and the library will only publish datasets.

**Comment by stefenmax** [comment]
But how long, will it be released in one week or month?

**Comment by Yueziyu** [comment]
The training code will be published by the first author, and the datasets in the article were built by me, so it will be published here.
I'm currently working on other things, so I don't know exactly when the code will be released.
